{{- if .Values.coapProxy.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-devicehive-coap-proxy
spec:
  selector:
    app: {{ .Release.Name }}-devicehive-coap-proxy
  type: {{ .Values.coapProxy.service.type }}
  ports:
    - protocol: UDP
      port: {{ .Values.coapProxy.service.port | int }}
      targetPort: coap
{{- end }}
