{{- if not .Values.backendNode.enabled }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-backend
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-backend"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.javaServer.backend.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-backend
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "devicehive.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end}}
      containers:
      - name: devicehive-backend
        image: "{{ .Values.javaServer.repository }}/devicehive-backend:{{ .Values.javaServer.tag }}"
        imagePullPolicy: {{ .Values.javaServer.pullPolicy }}
        env:
        {{- if eq .Values.javaServer.bus "rpc" }}
        - name: SPRING_PROFILES_ACTIVE
          value: "rpc-server"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Release.Name }}-kafka:9092"
        - name: DH_ZK_ADDRESS
          value: "{{ .Release.Name }}-zookeeper"
        - name: DH_ZK_PORT
          value: "2181"
        {{- else }}
        - name: DH_WS_PROXY
          value: "{{ .Release.Name }}-devicehive-ws-proxy-internal:3000"
        {{- end }}
        - name: DH_POSTGRES_ADDRESS
          value: "{{ .Release.Name }}-postgresql"
        - name: DH_POSTGRES_DB
          value: "{{ .Values.postgresql.postgresDatabase }}"
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "{{ .Values.postgresql.postgresUser }}"
        - name: DH_POSTGRES_PASSWORD
          value: "{{ .Values.postgresql.postgresPassword }}"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        - name: HC_MEMBERS
          value: "{{ .Release.Name }}-devicehive-hazelcast"
        - name: DH_LOG_LEVEL
          value: {{ .Values.javaServer.backend.dhLogLevel | quote }}
        - name: ROOT_LOG_LEVEL
          value: {{ .Values.javaServer.backend.rootLogLevel | quote }}
        resources:
{{ toYaml .Values.javaServer.backend.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
