kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-api-gateway-locations-conf
data:
  api-gateway.conf: |-
    location /api/rest/token {
        proxy_redirect off;
        proxy_pass http://auth_upstream/auth/rest/token;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /api/ {
        proxy_redirect off;
        proxy_pass http://api_upstream/api/;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_set_header Connection $connection_upgrade;
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /auth/ {
        proxy_redirect off;
        proxy_pass http://auth_upstream/auth/;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
{{- if .Values.javaServer.plugin.enabled }}
    location /api/rest/plugin {
        proxy_redirect off;
        proxy_pass http://plugin_upstream/plugin/rest/plugin;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /plugin/ {
        proxy_redirect off;
        proxy_pass http://plugin_upstream/plugin/;
        proxy_http_version 1.1;
        proxy_intercept_errors on;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Port $proxy_x_forwarded_port;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
    }
{{- end }}
{{- if .Values.wsProxy.external.enabled }}
    location /plugin/proxy {
        proxy_redirect off;
        proxy_pass http://wsproxyext/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
    }
{{- end }}
