{{- if .Values.ingress.enabled -}}
{{- $releaseName := .Release.Name -}}
{{- $javaServerPluginEnabled := .Values.javaServer.plugin.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "devicehive.fullname" . }}
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- end}}
  labels:
    app: {{ template "devicehive.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-proxy"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: /auth
        backend:
          serviceName: {{ $releaseName }}-devicehive-auth
          servicePort: 8090
      - path: /admin
        backend:
          serviceName: {{ $releaseName }}-devicehive-proxy
          servicePort: 8080
      - path: /api/rest/token
        backend:
          serviceName: {{ $releaseName }}-devicehive-auth
          servicePort: 8090
      - path: /api
        backend:
          serviceName: {{ $releaseName }}-devicehive-frontend
          servicePort: 8080
      {{- if $javaServerPluginEnabled }}
      - path: /plugin
        backend:
          serviceName: {{ $releaseName }}-devicehive-plugin
          servicePort: 8110
      - path: /plugin/proxy
        backend:
          serviceName: {{ $releaseName }}-devicehive-ws-proxy-external
          servicePort: 3000
      {{- end }}
  {{- end }}
{{- end -}}
