{{- if eq .Values.javaServer.bus "wsproxy" }}
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-devicehive-ws-proxy-internal
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "devicehive-ws-proxy"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
spec:
  replicas: {{ .Values.wsProxy.internal.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-devicehive-ws-proxy-internal
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "devicehive.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end}}
      containers:
      - name: devicehive-ws-proxy-internal
        image: {{ .Values.wsProxy.image | quote }}
        imagePullPolicy: {{ .Values.wsProxy.pullPolicy }}
        env:
        - name: ENVSEPARATOR
          value: '_'
        - name: KAFKA_KAFKA_HOSTS
          value: "{{ .Release.Name }}-kafka:9092"
        - name: PROXY_WEB_SOCKET_SERVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: ws-proxy
          containerPort: 3000
        resources:
{{ toYaml .Values.wsProxy.internal.resources | indent 10 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
