{
 "title": "DeviceHive containers",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Container memory usage, MiB",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service)(container_memory_usage_bytes{container_label_com_docker_compose_project!=\"\"}/1024/1024)",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container CPU usage, %",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (container_label_com_docker_compose_service)(rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_project!=\"\"}[1m])*100)",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container receive bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total{container_label_com_docker_compose_project!=\"\"}[1m])",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  },
  {
   "title": "Container transmit bytes/s",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(container_network_transmit_bytes_total{container_label_com_docker_compose_project!=\"\"}[1m])",
     "legendFormat": "{{ container_label_com_docker_compose_service }}"
    }
   ]
  }
 ]
}