javaServer:
  repository: devicehive
  tag: 3.5.0
  pullPolicy: IfNotPresent
  auth:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  backend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: INFO
  frontend:
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  hazelcast:
    minHeapSize: 512m
    maxHeapSize: 512m
    replicaCount: 1
    resources: {}
  plugin:
    enabled: false
    pluginConnectUrl: ""
    replicaCount: 1
    resources: {}
    dhLogLevel: INFO
    rootLogLevel: WARN
  # Connection method to Kafka
  # wsproxy: connect to Kafka via devicehive-ws-proxy, default
  # rpc: direct connection to Kafka
  bus: wsproxy

  ## JWT secret is used to sign and verify tokens
  ## If not set, a random 16 characters secret will be used
  jwtSecret: ""

ingress:
  enabled: false
  annotations: {}
  # kubernetes.io/ingress.class: nginx
  hosts: []

backendNode:
  enabled: false
  image: devicehive/devicehive-backend-node:development
  pullPolicy: IfNotPresent
  loggerLevel: info
  replicaCount: 1
  resources: {}

coapProxy:
  enabled: false
  image: devicehive/devicehive-coap-proxy:1.0.0
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 5683

mqttBroker:
  enabled: false
  image: devicehive/devicehive-mqtt:1.1.0
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  service:
    type: ClusterIP
    port: 1883
  appLogLevel: info

proxy:
  image: devicehive/devicehive-proxy:3.5.0
  pullPolicy: IfNotPresent
  replicaCount: 1
  resources: {}
  ingress:
    enabled: false
    annotations: {}
    #  kubernetes.io/ingress.class: nginx
    hosts: []

wsProxy:
  image: devicehive/devicehive-ws-proxy:1.1.0
  pullPolicy: IfNotPresent
  internal:
    replicaCount: 1
    resources: {}
  external:
    replicaCount: 1
    resources: {}

nodeSelector: {}

rbac:
  create: true
  serviceAccountName: default

# External dependencies
# PostgreSQL
postgresql:
  enabled: true
  postgresDatabase: devicehivedb
  postgresUser: devicehive
  postgresPassword: devicehivepassword
  persistence:
    enabled: true
    size: 1Gi
  imageTag: 10

# Apache Kafka
kafka:
  enabled: true

# Redis for syncronization between MQTT brokers
redis:
  # MQTT broker doesn't support password auth with Redis so disable it
  usePassword: false
