version: '3'
services:
  dh_proxy:
    ports:
      - "1883:1883"
    links:
      - mqtt_broker1
      - mqtt_broker2
    volumes:
      - "./nginx-mqtt-brokers.conf:/etc/nginx/stream.d/nginx-mqtt-brokers.conf:ro,Z"

  mqtt_broker1:
    image: devicehive/devicehive-mqtt:1.1.0
    links:
      - dh_frontend
      - redis
    restart: unless-stopped
    environment:
      - BROKER.WS_SERVER_URL=ws://dh_frontend:8080/api/websocket
      - BROKER.REDIS_SERVER_HOST=redis
      - BROKER.REDIS_SERVER_PORT=6379
      - BROKER.ENABLE_PM=false

  mqtt_broker2:
    image: devicehive/devicehive-mqtt:1.1.0
    links:
      - dh_frontend
      - redis
    restart: unless-stopped
    environment:
      - BROKER.WS_SERVER_URL=ws://dh_frontend:8080/api/websocket
      - BROKER.REDIS_SERVER_HOST=redis
      - BROKER.REDIS_SERVER_PORT=6379
      - BROKER.ENABLE_PM=false

  redis:
    image: redis:alpine
    restart: unless-stopped
