---
# 'admin-console-svc-loadbalancer.yaml' defines configuration for GCE
kind: Service
apiVersion: v1
metadata:
  name: dh-admin
spec:
  selector:
    app: devicehive-admin-console
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
...
