---
kind: Service
apiVersion: v1
metadata:
  name: dh-hazelcast
spec:
  selector:
    app: devicehive-hazelcast
  ports:
    - protocol: TCP
      port: 5701
      targetPort: hazelcast
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dh-hazelcast
  labels:
    name: dh-hazelcast
spec:
  template:
    metadata:
      labels:
        app: devicehive-hazelcast
    spec:
      containers:
      - name: devicehive-hazelcast
        image: devicehive/devicehive-hazelcast:development
        imagePullPolicy: Always
        env:
        - name: MIN_HEAP_SIZE
          value: "512m"
        - name: MAX_HEAP_SIZE
          value: "512m"
        ports:
        - name: hazelcast
          containerPort: 5701
---
kind: Service
apiVersion: v1
metadata:
  name: dh-auth
spec:
  selector:
    app: devicehive-auth-rdbms
  ports:
    - protocol: TCP
      port: 8090
      targetPort: devicehive-auth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-auth-rdbms
    spec:
      containers:
      - name: devicehive-auth-rdbms
        image: devicehive/devicehive-auth-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: JWT_SECRET
          value: "devicehive"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: devicehive-auth
          containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: dh-frontend
spec:
  selector:
    app: devicehive-frontend-rdbms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: devicehive-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-frontend-rdbms
    spec:
      containers:
      - name: devicehive-frontend-rdbms
        image: devicehive/devicehive-frontend-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_AUTH_URL
          value: "http://dh-auth:8090/api/rest"
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: JWT_SECRET
          value: "devicehive"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: devicehive-api
          containerPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-backend-rdbms
    spec:
      containers:
      - name: devicehive-backend-rdbms
        image: devicehive/devicehive-backend-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: api-gateway-upstream-conf
data:
  api-gateway.conf: |-
    upstream api_upstream {
        server dh-frontend:8080;
    }
    upstream auth_upstream {
        server dh-auth:8090;
    }
---
# dh-proxy service configuration depends on backing platform and stored in separate files.
# 'dh-proxy-svc-loadbalancer.yaml' defines configuration for GKE
# 'dh-proxy-svc-nodeport.yaml' defines configuration for Minicube
#---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-proxy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-proxy
    spec:
      containers:
      - name: devicehive-proxy
        image: devicehive/devicehive-proxy:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        livenessProbe:
          httpGet:
            path: /admin/
            port: http
          initialDelaySeconds: 60
          periodSeconds: 3
        volumeMounts:
        - name: api-gateway-upstream-conf
          mountPath: /etc/nginx/upstream.d
      volumes:
        - name: api-gateway-upstream-conf
          configMap:
            name: api-gateway-upstream-conf
            items:
            - key: api-gateway.conf
              path: api-gateway.conf
...
