---
kind: Service
apiVersion: v1
metadata:
  name: dh-hazelcast
spec:
  selector:
    app: devicehive-hazelcast
  ports:
    - protocol: TCP
      port: 5701
      targetPort: hazelcast
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: dh-hazelcast
  labels:
    name: dh-hazelcast
spec:
  template:
    metadata:
      labels:
        app: devicehive-hazelcast
    spec:
      containers:
      - name: devicehive-hazelcast
        image: devicehive/devicehive-hazelcast:development
        imagePullPolicy: Always
        env:
        - name: MIN_HEAP_SIZE
          value: "512m"
        - name: MAX_HEAP_SIZE
          value: "512m"
        ports:
        - name: hazelcast
          containerPort: 5701
---
kind: Service
apiVersion: v1
metadata:
  name: dh-auth
spec:
  selector:
    app: devicehive-auth-rdbms
  ports:
    - protocol: TCP
      port: 8090
      targetPort: devicehive-auth
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-auth
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-auth-rdbms
    spec:
      containers:
      - name: devicehive-auth-rdbms
        image: devicehive/devicehive-auth-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: JWT_SECRET
          value: "devicehive"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: devicehive-auth
          containerPort: 8090
---
kind: Service
apiVersion: v1
metadata:
  name: dh-frontend
spec:
  selector:
    app: devicehive-frontend-rdbms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: devicehive-api
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-frontend-rdbms
    spec:
      containers:
      - name: devicehive-frontend-rdbms
        image: devicehive/devicehive-frontend-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_AUTH_URL
          value: "http://dh-auth:8090/api/rest"
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: JWT_SECRET
          value: "devicehive"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
        ports:
        - name: devicehive-api
          containerPort: 8080
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-backend-rdbms
    spec:
      containers:
      - name: devicehive-backend-rdbms
        image: devicehive/devicehive-backend-rdbms:development
        imagePullPolicy: Always
        env:
        - name: DH_ZK_ADDRESS
          value: dh-bus-zookeeper
        - name: DH_ZK_PORT
          value: "2181"
        - name: DH_KAFKA_BOOTSTRAP_SERVERS
          value: dh-bus-kafka:9092
        - name: DH_POSTGRES_ADDRESS
          value: dh-db-postgresql
        - name: DH_POSTGRES_PORT
          value: "5432"
        - name: DH_POSTGRES_USERNAME
          value: "devicehive"
        - name: DH_POSTGRES_PASSWORD
          value: "devicehivepassword"
        - name: DH_POSTGRES_DB
          value: "devicehivedb"
        - name: HC_MEMBERS
          value: "dh-hazelcast"
        - name: HC_GROUP_NAME
          value: "dev"
        - name: HC_GROUP_PASSWORD
          value: "dev-pass"
---
# dh-admin service configuration depends on backing platform and stored in separate files.
# 'admin-console-svc-loadbalancer.yaml' defines configuration for GKE
# 'admin-console-svc-nodeport.yaml' defines configuration for Minicube
#---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dh-admin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: devicehive-admin-console
    spec:
      containers:
      - name: admin-console
        image: devicehive/admin-console:development
        imagePullPolicy: Always
        env:
        - name: DH_HOST
          value: dh-frontend
        - name: DH_PORT
          value: "8080"
        - name: DH_AUTH_HOST
          value: dh-auth
        - name: DH_AUTH_PORT
          value: "8090"
        ports:
        - name: http
          containerPort: 8080
        livenessProbe:
          httpGet:
            path: /admin/
            port: http
          initialDelaySeconds: 3
          periodSeconds: 3
...
