kind: Service
apiVersion: v1
metadata:
  name: kafka-zookeeper-zk
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: wurstmeister/zookeeper
        ports:
        - name: zk-client
          containerPort: 2181
        readinessProbe:
          tcpSocket:
            port: zk-client
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: zk-client
          initialDelaySeconds: 30
          periodSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: kafka-kf
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: devicehive/devicehive-kafka
        env:
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: "kafka-kf"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka-kf:9092"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "kafka-zookeeper-zk:2181"
        - name: DH_ZK_ADDRESS
          value: "kafka-zookeeper-zk"
        - name: DH_ZK_PORT
          value: "2181"
        ports:
        - name: kafka
          containerPort: 9092
        readinessProbe:
          tcpSocket:
            port: kafka
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: kafka
          initialDelaySeconds: 30
          periodSeconds: 10
...
